# Tomcat
server:
  port: 7706

# Spring
spring:
  application:
    # 应用名称
    name: pangu-iot-driver-audio-gxh
  profiles:
    # 环境配置
    active: @profiles.active@

logging:
  level:
    com.pangu.common.*: debug
    com.pangu.iot.*: debug

--- # nacos 配置
spring:
  cloud:
    nacos:
      # nacos 服务地址
      server-addr: @nacos.server@
      discovery:
        # 注册组
        group: @nacos.discovery.group@
        namespace: ${spring.profiles.active}
      config:
        # 配置组
        group: @nacos.config.group@
        namespace: ${spring.profiles.active}
  config:
    import:
      - optional:nacos:application-common.yml
      - optional:nacos:mq.yml
      - optional:nacos:${spring.application.name}.yml

driver:
  # 默认采用应用名称，唯一驱动标识，根据该名称自动实现创建或更新配置。 当项目名称修改时，需保留原名称，否则会创建新的驱动导致原有驱动配置丢失。
  name: ${spring.application.name}
  # 驱动显示名称
  display-name: 广播驱动
  project: @project.artifactId@
  description: @project.description@
  # 周期时间
  schedule:
    read: '2s'
    heartbeat: '10s'
  driver-attribute:
    - displayName: 主机
      name: host
      type: string
      value: 172.21.137.6
      description: http 主机地址
      option:
        type: input\select\checkox\switch\time...
        required: true
        data-type: static/url
        data: jsonString
    - displayName: 端口
      name: port
      type: int
      value: 80
      description: 端口号
      option:
        type: input\select\checkox\switch\time...
        required: true
        data-type: static/url
        data: jsonString
    - displayName: 用户名
      name: username
      type: string
      value: admin
      description: UserName
      option:
        type: input\select\checkox\switch\time...
        required: true
        data-type: static/url
        data: jsonString
    - displayName: 密码
      name: password
      type: string
      value: admin
      description: Passward
      option:
        type: input\select\checkox\switch\time...
        required: true
        data-type: static/url
        data: jsonString
  point-attribute:
    - displayName: 终端ID
      name: termID
      type: int
      value: 1
      description: 终端主键
      option:
        type: input\select\checkox\switch\time...
        required: true
        data-type: static/url
        data: jsonString
