spring:
  datasource:
    dynamic:
      # 设置默认的数据源或者数据源组,默认值即为 master
      primary: master
      datasource:
        # 主库数据源
        master:
          type: ${spring.datasource.type}
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: ${datasource.system-master.url}
          username: ${datasource.system-master.username}
          password: ${datasource.system-master.password}
        # 从库数据源
        # slave:
        #  type: ${spring.datasource.type}
        #  driver-class-name:
        #  url:
        #  username:
        #  password:
  rabbitmq:
    virtual-host: ${RABBITMQ_VIRTUAL_HOST:/}
    host: ${RABBITMQ_HOST:10.0.0.24}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:guest}
    password: ${RABBITMQ_PASSWORD:guest}
    publisher-confirm-type: correlated
    publisher-returns: true
    listener:
      simple:
        acknowledge-mode: manual
        retry:
          enabled: true

forest:
  variables:
    zbxServerIp: 10.0.0.24
    zbxServerPort: 8088
    zbxApiUrl: /zabbix/api_jsonrpc.php
    zbxApiToken: 40a51a3d510d93b1d98d4d647c915f3ba77cff13a61921a7e6cd2548a0e6484f



