# 未开启web服务，仅用于定义emqx客户端ID
server:
    port: 7701
udp:
  port: 6271

# Spring
spring:
  application:
    # 应用名称
    name: pangu-iot-driver-etone-ap
  profiles:
    # 环境配置
    active: @profiles.active@

--- # nacos 配置
spring:
  cloud:
    nacos:
      # nacos 服务地址
      server-addr: @nacos.server@
      discovery:
        # 注册组
        group: @nacos.discovery.group@
        namespace: ${spring.profiles.active}
      config:
        # 配置组
        group: @nacos.config.group@
        namespace: ${spring.profiles.active}
  config:
    import:
      - optional:nacos:application-common.yml
      - optional:nacos:mq.yml
      - optional:nacos:${spring.application.name}.yml


logging:
    level:
        com.pangu.common.*: debug
        com.pangu.iot.*: debug

driver:
    # 默认采用应用名称，唯一驱动标识，根据该名称自动实现创建或更新配置。 当项目名称修改时，需保留原名称，否则会创建新的驱动导致原有驱动配置丢失。
    name: ${spring.application.name}
    # 驱动显示名称
    display-name: 奕通AP定位驱动
    project: @project.artifactId@
    description: @project.description@
    # 周期时间
    schedule:
        heartbeat: '10s'
    point-attribute:
        - displayName: mac地址
          name: macAddress
          type: string
          value: ''
          description: mac地址
          option:
              type: input\select\checkox\switch\time...
              required: true
              data-type: static/url
              data: jsonString

