version: '3'

services:

  pangu-gateway:
    image: chengliang4810/pangu-gateway
    container_name: pangu-gateway
    restart: always
    networks:
      - pangu-network
    environment:
      # 时区上海
      TZ: Asia/Shanghai
      SPRING.PROFILES.ACTIVE: dev
      SPRING.CLOUD.NACOS.SERVER-ADDR: 10.0.0.34:8848
    ports:
      - "8080:8080"
    privileged: true

  pangu-auth:
    image: chengliang4810/pangu-auth
    container_name: pangu-auth
    restart: always
    networks:
      - pangu-network
    environment:
      # 时区上海
      TZ: Asia/Shanghai
      SPRING.PROFILES.ACTIVE: dev
      SPRING.CLOUD.NACOS.SERVER-ADDR: 10.0.0.34:8848
    ports:
      - "9210:9210"
    privileged: true

  pangu-system:
    image: chengliang4810/pangu-system
    container_name: pangu-system
    restart: always
    networks:
      - pangu-network
    environment:
      # 时区上海
      TZ: Asia/Shanghai
      SPRING.PROFILES.ACTIVE: dev
      SPRING.CLOUD.NACOS.SERVER-ADDR: 10.0.0.34:8848
    ports:
      - "9201:9201"
    privileged: true

  pangu-manager:
    image: chengliang4810/pangu-manager
    container_name: pangu-manager
    restart: always
    networks:
      - pangu-network
    environment:
      # 时区上海
      TZ: Asia/Shanghai
      SPRING.PROFILES.ACTIVE: dev
      SPRING.CLOUD.NACOS.SERVER-ADDR: 10.0.0.34:8848
    ports:
      - "7201:7201"
    privileged: true

  pangu-data:
    image: chengliang4810/pangu-data
    container_name: pangu-data
    restart: always
    networks:
      - pangu-network
    environment:
      # 时区上海
      TZ: Asia/Shanghai
      SPRING.PROFILES.ACTIVE: dev
      SPRING.CLOUD.NACOS.SERVER-ADDR: 10.0.0.34:8848
    ports:
      - "7202:7202"
    privileged: true

  pangu-ui:
    image: chengliang4810/pangu-ui
    container_name: pangu-ui
    restart: always
    networks:
      - pangu-network
    environment:
      # 时区上海
      TZ: Asia/Shanghai
      API_SERVER="http://10.0.0.34:8080/":
    ports:
      - "80:80"
    privileged: true

  pangu-driver-modbus-tcp:
    image: chengliang4810/pangu-driver-modbus-tcp
    container_name: pangu-driver-modbus-tcp
    restart: always
    networks:
      - pangu-network
    environment:
      # 时区上海
      TZ: Asia/Shanghai
      SPRING.PROFILES.ACTIVE: dev
      SPRING.CLOUD.NACOS.SERVER-ADDR: 10.0.0.34:8848
    logging:
      driver: "json-file"
      options:
        max-size: "2g"
    privileged: true

  pangu-driver-jemetech:
    image: chengliang4810/pangu-driver-jemetech
    container_name: pangu-driver-jemetech
    restart: always
    networks:
      - pangu-network
    environment:
      # 时区上海
      TZ: Asia/Shanghai
      SPRING.PROFILES.ACTIVE: dev
      SPRING.CLOUD.NACOS.SERVER-ADDR: 10.0.0.34:8848
    logging:
      driver: "json-file"
      options:
        max-size: "2g"
    privileged: true

  zabbix-server:
    image: zabbix/zabbix-server-mysql:6.4-alpine-latest
    container_name: zabbix-server
    networks:
      - pangu-network
    ports:
      - "10051:10051"
    environment:
      # 时区上海
      TZ: Asia/Shanghai
      ZBX_STARTCONNECTORS: 10
      DB_SERVER_HOST: 10.0.0.34
      MYSQL_USER: root
      MYSQL_PASSWORD: P@ssw0rd
    privileged: true

  zabbix-web:
    image: zabbix/zabbix-web-nginx-mysql:6.4-alpine-latest
    container_name: zabbix-web
    networks:
      - pangu-network
    ports:
      - "8088:8080"
    environment:
      # 时区上海
      TZ: Asia/Shanghai
      PHP_TZ: "Asia/Shanghai"
      ZBX_SERVER_HOST: zabbix-server
      DB_SERVER_HOST: 10.0.0.34
      MYSQL_USER: root
      MYSQL_PASSWORD: P@ssw0rd
    privileged: true

networks:
  pangu-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16
          gateway: 172.28.0.1
