# Tomcat
server:
  port: 7701

# Spring
spring:
  application:
    # 应用名称
    name: pangu-iot-test-driver
  profiles:
    # 环境配置
    active: @profiles.active@

mqtt:
  config:
    broker: tcp://10.0.0.34:1883
    userName: admin
    password: admin
    cleanSession: false
    reconnect: true
    timeout: 1000
    keepAlive: 60

--- # nacos 配置
spring:
  cloud:
    nacos:
      # nacos 服务地址
      server-addr: @nacos.server@
      discovery:
        # 注册组
        group: @nacos.discovery.group@
        namespace: ${spring.profiles.active}
      config:
        # 配置组
        group: @nacos.config.group@
        namespace: ${spring.profiles.active}
  config:
    import:
      - optional:nacos:application-common.yml
      - optional:nacos:mq.yml
      - optional:nacos:${spring.application.name}.yml



