# Tomcat
server:
  port: 7201

# Spring
spring:
  application:
    # 应用名称
    name: pangu-iot-manager
  profiles:
    # 环境配置
    active: @profiles.active@

logging:
  level:
    com.pangu.common.*: debug
    com.pangu.iot.*: debug


--- # nacos 配置
spring:
  cloud:
    nacos:
      # nacos 服务地址
      server-addr: @nacos.server@
      discovery:
        # 注册组
        group: @nacos.discovery.group@
        namespace: ${spring.profiles.active}
      config:
        # 配置组
        group: @nacos.config.group@
        namespace: ${spring.profiles.active}
  config:
    import:
      - optional:nacos:application-common.yml
      - optional:nacos:datasource.yml
      - optional:nacos:mq.yml
      - optional:nacos:${spring.application.name}.yml
