driver:
  tenant: '000000'
  name: Modbus-Tcp驱动
  code: ModbusTcpDriver
  remark: @project.description@
  schedule:
    # 定时读数据
    read:
      enable: true
      corn: '0/10 * * * * ?'
    # 网关设备状态
    gateway:
      enable: true
      corn: '0/30 * * * * ?'
    custom:
      enable: true
      corn: '0/30 * * * * ?'
  driver-attribute:
    - display-name: 主机
      attribute-name: host
      attribute-type-flag: STRING
      default-value: localhost
      remark: Modbus IP
    - display-name: 端口
      attribute-name: port
      attribute-type-flag: INT
      default-value: 502
      remark: Modbus Port
  point-attribute:
    - display-name: 从站编号
      attribute-name: slaveId
      attribute-type-flag: INT
      default-value: 1
      remark: 从站编号
    - display-name: 功能码
      attribute-name: functionCode
      attribute-type-flag: INT
      default-value: 1
      remark: 功能码 [1、2、3、4]
    - display-name: 偏移量
      attribute-name: offset
      attribute-type-flag: INT
      default-value: 0
      remark: 偏移量

# Tomcat
server:
  port: 9801

# Spring
spring:
  application:
    # 应用名称
    name: ruoyi-driver-modbus-tcp
  profiles:
    # 环境配置
    active: @profiles.active@

--- # nacos 配置
spring:
  cloud:
    nacos:
      # nacos 服务地址
      server-addr: @nacos.server@
      discovery:
        # 注册组
        group: @nacos.discovery.group@
        namespace: ${spring.profiles.active}
      config:
        # 配置组
        group: @nacos.config.group@
        namespace: ${spring.profiles.active}
  config:
    import:
      - optional:nacos:application-common.yml
      - optional:nacos:datasource.yml
      - optional:nacos:${spring.application.name}.yml
