name: Maven Build and Docker Push
on:
  push:
    branches:
      - master

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Cache Maven dependencies
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'

      - name: Get version from pom.xml
        id: version
        run: echo "::set-output name=version::$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)"

      - name: Build with Maven And Build Docker Images
        run: |
          mvn clean install -DskipTests
          docker build -t ${{ secrets.DOCKER_USERNAME }}/pangu-gateway:latest           -t ${{ secrets.DOCKER_USERNAME }}/pangu-gateway:${{ steps.version.outputs.version }}             -f pangu-gateway/Dockerfile ./pangu-gateway/
          docker build -t ${{ secrets.DOCKER_USERNAME }}/pangu-auth:latest              -t ${{ secrets.DOCKER_USERNAME }}/pangu-auth:${{ steps.version.outputs.version }}                -f pangu-auth/Dockerfile ./pangu-auth/
          docker build -t ${{ secrets.DOCKER_USERNAME }}/pangu-system:latest            -t ${{ secrets.DOCKER_USERNAME }}/pangu-system:${{ steps.version.outputs.version }}              -f pangu-modules/pangu-system//Dockerfile ./pangu-modules/pangu-system/
          docker build -t ${{ secrets.DOCKER_USERNAME }}/pangu-manager:latest           -t ${{ secrets.DOCKER_USERNAME }}/pangu-manager:${{ steps.version.outputs.version }}             -f pangu-iot/pangu-iot-manager/Dockerfile ./pangu-iot/pangu-iot-manager/
          docker build -t ${{ secrets.DOCKER_USERNAME }}/pangu-data:latest              -t ${{ secrets.DOCKER_USERNAME }}/pangu-data:${{ steps.version.outputs.version }}                -f pangu-iot/pangu-iot-data/Dockerfile ./pangu-iot/pangu-iot-data/
          docker build -t ${{ secrets.DOCKER_USERNAME }}/pangu-driver-modbus-tcp:latest -t ${{ secrets.DOCKER_USERNAME }}/pangu-driver-modbus-tcp:${{ steps.version.outputs.version }}   -f pangu-iot-driver/pangu-iot-modbus-tcp-driver/Dockerfile ./pangu-iot-driver/pangu-iot-modbus-tcp-driver/
          docker build -t ${{ secrets.DOCKER_USERNAME }}/pangu-driver-jemetech:latest   -t ${{ secrets.DOCKER_USERNAME }}/pangu-driver-jemetech:${{ steps.version.outputs.version }}     -f pangu-iot-driver/pangu-iot-driver-jemetech/Dockerfile ./pangu-iot-driver/pangu-iot-driver-jemetech/
          docker build -t ${{ secrets.DOCKER_USERNAME }}/pangu-driver-etone-ap:latest   -t ${{ secrets.DOCKER_USERNAME }}/pangu-driver-etone-ap:${{ steps.version.outputs.version }}     -f pangu-iot-driver/pangu-iot-driver-etone-ap/Dockerfile ./pangu-iot-driver/pangu-iot-driver-etone-ap/

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker images to Docker Hub
        uses: docker/build-push-action@v4.0.0
        with:
         context: .
         push: true
         tags: |
              ${{ secrets.DOCKER_USERNAME }}/pangu-gateway:latest
              ${{ secrets.DOCKER_USERNAME }}/pangu-gateway:${{ steps.version.outputs.version }}
              ${{ secrets.DOCKER_USERNAME }}/pangu-auth:latest
              ${{ secrets.DOCKER_USERNAME }}/pangu-auth:${{ steps.version.outputs.version }}
              ${{ secrets.DOCKER_USERNAME }}/pangu-system:latest
              ${{ secrets.DOCKER_USERNAME }}/pangu-system:${{ steps.version.outputs.version }}
              ${{ secrets.DOCKER_USERNAME }}/pangu-manager:latest
              ${{ secrets.DOCKER_USERNAME }}/pangu-manager:${{ steps.version.outputs.version }}
              ${{ secrets.DOCKER_USERNAME }}/pangu-data:latest
              ${{ secrets.DOCKER_USERNAME }}/pangu-data:${{ steps.version.outputs.version }}
              ${{ secrets.DOCKER_USERNAME }}/pangu-driver-modbus-tcp:latest
              ${{ secrets.DOCKER_USERNAME }}/pangu-driver-modbus-tcp:${{ steps.version.outputs.version }}
              ${{ secrets.DOCKER_USERNAME }}/pangu-driver-jemetech:latest
              ${{ secrets.DOCKER_USERNAME }}/pangu-driver-jemetech:${{ steps.version.outputs.version }}
              ${{ secrets.DOCKER_USERNAME }}/pangu-driver-etone-ap:latest
              ${{ secrets.DOCKER_USERNAME }}/pangu-driver-etone-ap:${{ steps.version.outputs.version }}
