name: Maven Build and Docker Push
on:
  push:
    branches:
      - master

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Cache Maven dependencies
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'

      - name: Build with Maven
        run: mvn clean install -DskipTests

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Get version from package.json
        id: version
        run: echo "::set-output name=version::$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)"

      - name: Pangu-Auth Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./pangu-auth/
          file: ./pangu-auth/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/pangu-auth:${{ steps.version.outputs.version }},${{ secrets.DOCKER_USERNAME }}/pangu-auth:latest

      - name: Pangu-Gateway Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./pangu-gateway/
          file: ./pangu-gateway/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/pangu-gateway:${{ steps.version.outputs.version }},${{ secrets.DOCKER_USERNAME }}/pangu-gateway:latest

      - name: Pangu-System Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./pangu-modules/pangu-system/
          file: ./pangu-modules/pangu-system/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/pangu-system:${{ steps.version.outputs.version }},${{ secrets.DOCKER_USERNAME }}/pangu-system:latest

      - name: Pangu-IOT-Manager Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./pangu-iot/pangu-iot-manager/
          file: ./pangu-iot/pangu-iot-manager/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/pangu-manager:${{ steps.version.outputs.version }},${{ secrets.DOCKER_USERNAME }}/pangu-manager:latest

      - name: Pangu-IOT-Data Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./pangu-iot/pangu-iot-data/
          file: ./pangu-iot/pangu-iot-data/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/pangu-data:${{ steps.version.outputs.version }},${{ secrets.DOCKER_USERNAME }}/pangu-data:latest

      - name: Pangu-IOT-Driver-Modbus-tcp Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./pangu-iot-driver/pangu-iot-modbus-tcp-driver/
          file: ./pangu-iot-driver/pangu-iot-modbus-tcp-driver/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/pangu-driver-modbus-tcp:${{ steps.version.outputs.version }},${{ secrets.DOCKER_USERNAME }}/pangu-modbus-tcp:latest
